# Generated by Django 5.1.4 on 2025-01-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_inventory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'позицию инвентаря', 'verbose_name_plural': 'Инвентарь'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_status',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
