# Generated by Django 5.1.4 on 2025-01-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_inventory_options_inventory_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_status',
            field=models.CharField(choices=[('сломанный', 'сломанный'), ('новый', 'новый'), ('сломанный', 'сломанный')], default='новый', max_length=9),
        ),
    ]
