# Generated by Django 5.1.4 on 2025-01-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_inventory_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('count', models.IntegerField(default=0)),
                ('provider', models.CharField(max_length=256)),
            ],
        ),
    ]
