# Generated by Django 5.1.4 on 2025-01-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_application', models.IntegerField()),
                ('status_application', models.CharField(choices=[('необработана', 'необработана'), ('одобрена', 'одобрена'), ('отклонена', 'отклонена')], default='необработана', max_length=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'позицию плана', 'verbose_name_plural': 'План инвенторя'},
        ),
    ]
